name: Merge & Post Video to Facebook

on:
  schedule:
    # This cron job runs at 5:30 AM UTC (which is 11:00 AM IST)
    - cron: '30 5 * * *'
    # This cron job runs at 1:30 PM UTC (which is 7:00 PM IST)
    - cron: '30 13 * * *'
  workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab.

jobs:
  post-video:
    runs-on: ubuntu-latest # The type of runner that the job will run on. Ubuntu is a good choice.

    steps:
    - name: Checkout repository # Step 1: Get your code from the repository
      uses: actions/checkout@v4

    - name: Set up Python # Step 2: Configure the Python environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version available

    - name: Install system dependencies (for FFmpeg) # Step 3: Install FFmpeg, crucial for moviepy
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    # --- IMPORTANT CHANGE HERE ---
    - name: Clean Python cache and Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip cache purge # Add this line to clear pip cache
        pip install cloudinary moviepy requests
    # --- END IMPORTANT CHANGE ---

    - name: Restore posted media cache
      uses: actions/cache/restore@v4
      with:
        path: posted_media_tracker.json
        key: ${{ runner.os }}-posted-media-cache-${{ hashFiles('**/*.py') }}
        restore-keys: |
          ${{ runner.os }}-posted-media-cache-

    - name: Run video merge and Facebook post script
      env:
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        PAGE_ID: ${{ secrets.PAGE_ID }}
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
      run: python merge_and_post_to_facebook.py

    - name: Save posted media cache
      uses: actions/cache/save@v4
      with:
        path: posted_media_tracker.json
        key: ${{ runner.os }}-posted-media-cache-${{ hashFiles('**/*.py') }}
      if: success()
